version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    environment:
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_DATABASE}
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
      - WATCHPACK_POLLING=true
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - social.net

  db:
    image: postgres:17.3-alpine
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - network-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    command: >
      postgres -c wal_level=logical
               -c max_wal_senders=10
               -c max_replication_slots=10
    restart: unless-stopped
    networks:
      - social.net

  db-dw:
    image: postgres:17.3-alpine
    container_name: db-dw
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DBWH_USERNAME}
      POSTGRES_PASSWORD: ${DBWH_PASSWORD}
      POSTGRES_DB: ${DBWH_DATABASE}
    ports:
      - "5433:5432"
    volumes:
      - pg_dw_data:/var/lib/postgresql/data
      - ./dw/init:/docker-entrypoint-initdb.d
    depends_on:
      - db
    networks:
      - social.net

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - social.net
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      retries: 3
      timeout: 3s

  rabbitmq:
    image: rabbitmq:4.0.7-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    networks:
      - social.net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
    networks:
      - social.net

volumes:
  pg_dw_data:
    name: pg_dw_data
  network-data:
    name: network-data
  redis:
    name: network-redis
  es_data:
    name: elasticsearch-data

networks:
  social.net:
    external: true
