import {
  faHouse,
  faCompass,
  faCommentDots,
  faBell,
  faPlusSquare,
  faCirclePlay,
  faHeart,
  faComment,
  faPaperPlane,
  faBookmark,
  faMoon,
  faFlag,
  faFaceSmile,
  faImage
} from '@fortawesome/free-regular-svg-icons';
import {
  faSearch,
  faBars,
  faHeart as faHeartSolid,
  faBookmark as faBookmarkSolid,
  faCheck,
  faEllipsis,
  faGear,
  faChartLine,
  faUserGroup,
  faRightFromBracket,
  faXmark,
  faSpinner,
  faChevronUp,
  faChevronDown,
  faTriangleExclamation

} from '@fortawesome/free-solid-svg-icons';

export const Icons = {
  home: faHouse,
  search: faSearch,
  explore: faCompass,
  reels: faCirclePlay,
  messages: faCommentDots,
  notifications: faBell,
  create: faPlusSquare,
  menu: faBars,
  heartWhite: faHeart,
  heartRed: faHeartSolid,
  comment: faComment,
  share: faPaperPlane,
  saveWhite: faBookmark,
  saveBlack: faBookmarkSolid,
  check: faCheck,
  more: faEllipsis,
  settings: faGear,
  activity: faChartLine,
  bookmark: faBookmark,
  moon: faMoon,
  flag: faFlag,
  switch: faUserGroup,
  logout: faRightFromBracket,
  close: faXmark,
  emoji: faFaceSmile,
  image: faImage,
  spinner: faSpinner,
  chevronUp: faChevronUp,   
  chevronDown: faChevronDown,
  warning: faTriangleExclamation
};
